const KEYCODE_MENU = 82;
const KEYCODE_POWER = 26;
const KEYCODE_VOLUME_DOWN = 25;
const KEYCODE_VOLUME_UP = 24;
const KEYCODE_BACK = 4;
const KEYCODE_ENTER = 66;
const KEYCODE_DOWN = 0;

module.exports = {
  KEYCODE_MENU,
  KEYCODE_POWER,
  KEYCODE_VOLUME_DOWN,
  KEYCODE_VOLUME_UP,
  KEYCODE_BACK,
  KEYCODE_DOWN,
  KEYCODE_ENTER,
};
